#!/bin/bash

SAMPLE_TEXT="algo\ncosa\n\ntecho\n"

echo "1..1"

bail_out() {
  echo $1
  exit 1
}

assert_eq() {
  if diff=$( diff -y <( echo -e "$1" ) <( echo -e "$2" ) )
  then echo "ok 1 $3"
  else
    echo -e "not ok 1 -\n$diff"
  fi
}

[[ -x ./examples/prepend_text ]] || bail_out "Bail out! examples not available"

assert_eq "$(echo -ne $SAMPLE_TEXT | ./examples/prepend_text beep)" \
  "beep algo\nbeep cosa\n\nbeep techo" \
  "prepend text works"
